name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main   # لو الفرع الأساسي اسمه main، لو master غيري الاسم

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF || '' }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL || '' }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY || ''}}

    steps:
      # 1. نسخ المشروع
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. إعداد Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. تثبيت الحزم
      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      # 4. بناء المشروع
      - name: Build project
        run: |
          cd frontend
          npm run build

      # 5. نشر على GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
